apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-service
  annotations:
    github.com/project-slug: Octo-sv-organization/backstage-service
spec:
  type: other
  lifecycle: unknown
